###
# Get all users
GET http://localhost:3000/users/

###
# Get user by id
GET http://localhost:3000/users/32307754e72d1ae5b744625

###
# Create User
POST http://localhost:3000/users/
Content-Type: application/json

{
    "firstName": "Bruce",
    "lastName": "Wayne",
    "email": "batman@gmail.com",
    "role": "admin"
}