version: '3'
services:
  mono-app-1:
    container_name: forge-app
    build:
      context: .
      args:
        - APP=forge
    restart: always
    ports:
      - 3000:3000
# run this
# docker-compose up -d
