version: '3'
services:
  mono-app-1:
    container_name: forge-app
    build:
      context: .
      args:
        - APP=forge
        - EXE_PORT=3005
    restart: always
    ports:
      - 3005:3005
# run this
# docker-compose up -d
