# #############################################
# ##! Need to run below commands
# # sudo docker build -f apps/forge/Dockerfile -t forge .
# # sudo docker build -f apps/course/Dockerfile -t course .
# # sudo docker build -f apps/learner/Dockerfile -t learner .
# # sudo docker build -f apps/notifications/Dockerfile -t notifications .
# # sudo docker build -f apps/payment/Dockerfile -t payment .
# # sudo docker compose up
# # sudo docker compose down

##*###############################
# version: '3.8'
# services:
#   app0:
#     image: forge
#     ports:
#       - 3005:3005
#     environment:
#       - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
#     networks:
#       - my-network

#   app1:
#     image: learner
#     ports:
#       - 3001:3001
#     environment:
#       - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
#     networks:
#       - my-network

#   app2:
#     image: payment
#     ports:
#       - 3002:3002
#     environment:
#       - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
#     networks:
#       - my-network

#   app3:
#     image: course
#     ports:
#       - 3003:3003
#     environment:
#       - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
#     networks:
#       - my-network

#   app4:
#     image: notifications
#     ports:
#       - 3004:3004
#     environment:
#       - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
#     networks:
#       - my-network

# networks:
#   my-network:
#     driver: bridge

##*#################################
version: '3.8'
services:
  forge:
    build:
      context: ./
      dockerfile: ./apps/forge/Dockerfile
    ports:
      - 3005:3005
    environment:
      - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
    networks:
      - my-network

  course:
    build:
      context: ./
      dockerfile: ./apps/course/Dockerfile
    ports:
      - 3003:3003
    environment:
      - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
    networks:
      - my-network

  notifications:
    build:
      context: ./
      dockerfile: ./apps/notifications/Dockerfile
    ports:
      - 3004:3004
    environment:
      - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
    networks:
      - my-network

  payment:
    build:
      context: ./
      dockerfile: ./apps/payment/Dockerfile
    ports:
      - 3004:3004
    environment:
      - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
    networks:
      - my-network

  learner:
    build:
      context: ./
      dockerfile: ./apps/learner/Dockerfile
    ports:
      - 3004:3004
    environment:
      - ATLAS_URI=mongodb+srv://admin-rusira:IHQDVutU3zZzxJCQ@forgedb.hzkstby.mongodb.net/
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
